### ISSUE TITLE
4. additional testimonials

### ISSUE THREAD

**Issue by shatfield4** [shatfield4/iCyberSecurity#4]
As a product seller, I want my customers to be able to add their own testimonials.

Detailed Description: On bottom of the same page where customers view other customers satisfied testimonials, add a box where the customers can submit their testimonials. Once submitted their testimonials will come up on the top for others to view.

Tasks:
1.Create 2 boxes, each one for the name and the testimonial.
2. Create a submit button. When pressed the program will check to see if any text has been written on both boxes. If one or both has nothing written an error will pop up to have the customer enter something.
3. Once submitted the testimonial should be posted on the top of the list with the name and testimonial along with the time submitted automatically.

Tests:
1. Check if the error works for when the one or both the boxes are empty and pressed the submit button.
2. Check if the testimonial appears exactly as submitted and aligned properly with other testimonials.

Done: When the testimonial appears exactly as submitted with proper format. Also the error check properly works when submitted.

**Comment by ayako54** [comment]
//if using submit boxes
Want to share your experience with us? 
Please fill out the form below with your name or nickname and your story!

Name/Nickname to appear: (box)

Your story: (another bigger box)

(submit button)
Thank you very much!

//if using email/mail
Want to share your experience with us? 
Please send us your story by email or mail to the following address below.
Also please include your name to appear on out testimonial page along with your story. 
Thank you very much!

iCyberSecurity's email
ICyberSecurity's mailing address
